### ISSUE TITLE
Parse "options.extra_requires" and put reqs under "other"

### ISSUE THREAD

**Issue by nikitalita** [plus3it/pyppyn#303]
**Is your feature request related to a problem? Please describe.**
get_required() should not return packages which are not required for the install. packages listed under "options.extra_requires" are listed in get_required(). 

For example:
https://github.com/miurahr/aqtinstall/blob/master/setup.cfg

Every package listed in under that is listed under "options.extra_requires" is listed in get_required().

**Describe the solution you'd like**
Parse "options.extra_requires" and put the reqs listed there under "other"

**Comment by lorengordon** [comment]
@nikitalita Thanks for the issue. I see what you mean for the package you are referencing. However, I've also seen packages where the user may well want "extras_require" packages included. I think we would need an argument or config setting for the user to indicate intention.

If you have a chance to think about an implementation and open a PR, I'd be happy to review and provide guidance.

Also this kind of change would be backwards incompatible, and we'd need to consider the impact where we are actively using this library ourselves...

https://github.com/plus3it/gravitybee/blob/e16950e1ab039bcd0f23849c469f3380f2654026/gravitybee/__init__.py#L481

**Comment by nikitalita** [comment]
Ok, maybe you could add an option to get_required() to have it exclude extras? Either way, I think the requires in extra_requires should be parsed somehow, and not just dumped into "unparsed"; perhaps a new category instead of "other" called "extras" and that is included by default in `get_required()`?

**Comment by lorengordon** [comment]
Yeah, makes sense. Would you want something like:

```
{
  'extras': {
    <label>: [<pkgs>]
  }
}
```

That way each label would map directly to the `extras_required` map?

I think we could do that by default, but _also_ on `get_required()` add an `include_extras_required=True` arg that keeps the current behavior.

**Comment by nikitalita** [comment]
> That way each label would map directly to the `extras_require` map from setup.cfg/setup.py?
Yeah, I think that would be best; the user may want to include certain categories of extras, but not others.

> I think we could do that by default, but _also_ on `get_required()` add an `include_extras_require=True` arg that keeps the current behavior.

Yes, I agree; my assumption was that `get_required()` only listed the requirements to run the package on the system, not the extras.
