### ISSUE TITLE
Use `packaging` to parse markers and add compound marker support

### ISSUE THREAD

**Issue by nikitalita** [plus3it/pyppyn#310]
**Is your feature request related to a problem? Please describe.**
pyppyn currently doesn't parse compound markers at all. This leads to packages erroneously being included in `get_required()` under "unparsed".

**Describe the solution you'd like**
Instead of trying to reimplement a PEP 496 parser/checker, why don't we just use the `packaging` package? This would enable  easy compound marker parsing. As for groups, we could extend the `Marker` class to get a function to return a dictionary of the individual groups (python_version, platform, etc.)

If possible version conflict is a problem, we could do something like what pip does and include it as a vendor package (like here: https://github.com/pypa/setuptools/blob/main/pkg_resources/_vendor/packaging/markers.py)

**Describe alternatives you've considered**
We could just reimplement it ourselves, but why bother when it's already written?

**Comment by lorengordon** [comment]
Archiving project. See: https://github.com/plus3it/gravitybee/issues/486#issuecomment-1414501191
